import { ANSWER_MODELS, REASONING_EFFORTS, reasoningOptions } from '../shared/models.js';
import { MAX_CONTEXT_CHARACTERS } from '../shared/tasks.js';
import { z } from 'zod';
import { DEFAULT_SETTINGS } from '../shared/defaults.js';

const language = z
  .string()
  .max(12)
  .regex(/^$|^[a-z]{2,3}(?:-[a-z]{2,4})?$/i);
const model = z
  .string()
  .min(1)
  .max(100)
  .regex(/^[a-zA-Z0-9._:-]+$/);
export const settingsSchema = z
  .object({
    answerBilling: z.enum(['api', 'chatgpt']).default('api'),
    model: z.enum(ANSWER_MODELS),
    reasoningEffort: z.enum(REASONING_EFFORTS).default(DEFAULT_SETTINGS.reasoningEffort),
    fastMode: z.boolean().default(false),
    transcriptionModel: model,
    transcriptionProvider: z.enum(['local', 'openai']).default('local'),
    language,
    systemPrompt: z.string().max(12000),
    autoPrompt: z.string().max(12000),
    context: z.string().max(MAX_CONTEXT_CHARACTERS),
    maxOutputTokens: z.number().int().min(1).max(100000).nullable().default(null),
    autoTriggerSource: z.enum(['system', 'mic', 'either']).default('system'),
    autoCooldownMs: z.number().int().min(1000).max(120000),
    captureMode: z.enum(['realtime', 'diarized']),
    captureMic: z.boolean(),
    captureSystem: z.boolean(),
    filterMicrophoneEcho: z.boolean().default(true),
    diarizationProvider: z.enum(['off', 'local', 'openai']).default('local'),
    backgroundSpeakers: z.boolean().default(true),
    micDeviceId: z.string().max(500),
    systemDeviceId: z.string().max(500).default(''),
    micLabel: z.string().max(80),
    systemLabel: z.string().max(80),
    diarizationChunkSeconds: z.number().min(3).max(30),
  })
  .refine((settings) => reasoningOptions(settings.model).includes(settings.reasoningEffort), {
    message: 'Unsupported reasoning strength for this model',
    path: ['reasoningEffort'],
  })
  .default(DEFAULT_SETTINGS);
export const answerSchema = z.object({
  settings: settingsSchema,
  transcript: z
    .array(
      z.object({
        id: z.string().max(200),
        source: z.enum(['mic', 'system']),
        speaker: z.string().max(200),
        text: z.string().max(12000),
        timestamp: z.number().finite().nonnegative(),
        endTimestamp: z.number().finite().nonnegative().optional(),
        turnId: z.string().max(250).optional(),
        speakerId: z.string().max(200).optional(),
        attribution: z.enum(['reference', 'chunk', 'local']).optional(),
        final: z.boolean(),
      }),
    )
    .max(2000),
  question: z.string().max(6000).default(''),
  mode: z.enum(['manual', 'auto']),
  previousSuggestions: z.array(z.string().max(8000)).max(30).default([]),
  demo: z.boolean().default(false),
});
export const keySchema = z.object({
  remember: z.boolean().default(false),
  apiKey: z
    .string()
    .trim()
    .max(500)
    .refine(
      (value) => value === '' || /^[\x21-\x7e]{12,500}$/.test(value),
      'Invalid API key format',
    ),
});
export const configureSchema = z.object({
  type: z.literal('configure'),
  model: z.enum([
    'gpt-live-transcribe',
    'gpt-transcribe',
    'gpt-4o-transcribe',
    'gpt-4o-mini-transcribe',
    'gpt-4o-mini-transcribe-2025-12-15',
  ]),
  language: language.default(''),
});
export type RealtimeConfig = z.infer<typeof configureSchema>;
export const audioEventSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('input_audio_buffer.append'),
    audio: z
      .string()
      .min(4)
      .max(256000)
      .regex(/^[A-Za-z0-9+/]+={0,2}$/),
  }),
  z.object({ type: z.literal('input_audio_buffer.commit') }),
]);
export const diarizeSchema = z.object({
  audio: z
    .string()
    .min(60)
    .max(4000000)
    .regex(/^[A-Za-z0-9+/]+={0,2}$/),
  source: z.enum(['mic', 'system']),
  chunkId: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[\w-]+$/),
  timestamp: z.number().finite().nonnegative(),
  language: language.default(''),
  knownSpeakers: z
    .array(
      z.object({
        name: z.string().regex(/^speaker_[1-4]$/),
        audio: z
          .string()
          .min(60)
          .max(640064)
          .regex(/^[A-Za-z0-9+/]+={0,2}$/),
      }),
    )
    .max(4)
    .refine(
      (speakers) => new Set(speakers.map((speaker) => speaker.name)).size === speakers.length,
      'Speaker references must have unique names',
    )
    .optional(),
});

/** Accept only canonical WAV PCM16 mono 24kHz generated by our capture pipeline. */
export function decodeWav(encoded: string): Buffer {
  const data = Buffer.from(encoded, 'base64');
  if (
    data.toString('base64') !== encoded ||
    data.length < 4844 ||
    data.length > 2_880_044 ||
    data.toString('ascii', 0, 4) !== 'RIFF' ||
    data.toString('ascii', 8, 12) !== 'WAVE' ||
    data.toString('ascii', 12, 16) !== 'fmt ' ||
    data.readUInt32LE(16) !== 16 ||
    data.readUInt16LE(20) !== 1 ||
    data.readUInt16LE(22) !== 1 ||
    data.readUInt32LE(24) !== 24000 ||
    data.readUInt32LE(28) !== 48000 ||
    data.readUInt16LE(32) !== 2 ||
    data.readUInt16LE(34) !== 16 ||
    data.toString('ascii', 36, 40) !== 'data' ||
    data.readUInt32LE(40) !== data.length - 44 ||
    data.readUInt32LE(4) !== data.length - 8 ||
    (data.length - 44) % 2 !== 0
  ) {
    throw new Error('Invalid audio. Expected mono WAV, PCM16, 24 kHz (up to 60 seconds).');
  }
  return data;
}
