import type { Settings } from './types.js';
import { DEFAULT_TASK_PROMPT, DEFAULT_AUTO_PROMPT } from './tasks.js';
export const DEFAULT_SETTINGS: Settings = {
  model: 'gpt-6-luna',
  reasoningEffort: 'none',
  fastMode: false,
  transcriptionModel: 'gpt-live-transcribe',
  language: '',
  systemPrompt: DEFAULT_TASK_PROMPT,
  autoPrompt: DEFAULT_AUTO_PROMPT,
  context: '',
  maxOutputTokens: null,
  autoTriggerSource: 'system',
  autoCooldownMs: 8000,
  captureMode: 'realtime',
  captureMic: true,
  captureSystem: true,
  filterMicrophoneEcho: true,
  backgroundSpeakers: true,
  micDeviceId: '',
  systemDeviceId: '',
  micLabel: 'Me',
  systemLabel: 'Other speaker',
  diarizationChunkSeconds: 12,
};
